language: java

jdk:
  # Ideally this would use openjdk8, but no such option exists at this time.
  - oraclejdk8

notifications:
  email:
    - services@wikimedia.org

# We need a new libstdc++ than Ubuntu 12.04 LTS Server offers.
sudo: required
dist: trusty
